services:
  - type: web
    name: muvidb-media-extractor
    env: docker
    rootDir: services/media-extractor
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: EXTRACTOR_SECRET
        generateValue: true
