type FilmCredit = {
  role?: string | null;
  character_name?: string | null;
  films?: {
    title?: string | null;
    year?: number | null;
    view_count?: number | null;
    average_rating?: number | null;
  } | null;
};

export type ProfessionalCvData = {
  format: 'resume' | 'detailed';
  person: {
    name: string;
    bio?: string | null;
    biography?: string | null;
    nationality?: string | null;
    known_for_department?: string | null;
    profile_views?: number | null;
    slug?: string | null;
  };
  email?: string | null;
  professionalRoles?: string[];
  credits: FilmCredit[];
  generatedAt?: Date;
};

const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const MARGIN = 44;

function ascii(value: unknown) {
  return String(value ?? '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[–—−]/g, '-')
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/[^\x20-\x7E]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function pdfText(value: unknown) {
  return ascii(value).replace(/([\\()])/g, '\\$1');
}

function roleLabel(value: unknown) {
  return ascii(value).replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function number(value: unknown) {
  return Math.max(0, Number(value) || 0).toLocaleString('en-US');
}

function wrap(value: unknown, maxChars: number) {
  const words = ascii(value).split(' ').filter(Boolean);
  const lines: string[] = [];
  let current = '';
  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (candidate.length <= maxChars) current = candidate;
    else {
      if (current) lines.push(current);
      current = word;
    }
  }
  if (current) lines.push(current);
  return lines;
}

function text(x: number, y: number, size: number, value: unknown, bold = false, color = '0.12 0.13 0.15') {
  return `${color} rg BT /${bold ? 'F2' : 'F1'} ${size} Tf 1 0 0 1 ${x} ${y} Tm (${pdfText(value)}) Tj ET`;
}

function line(x1: number, y1: number, x2: number, y2: number, color = '0.86 0.87 0.89') {
  return `${color} RG 0.7 w ${x1} ${y1} m ${x2} ${y2} l S`;
}

function pageHeader(name: string, subtitle: string) {
  return [
    '0.96 0.29 0.08 rg 0 772 595 70 re f',
    text(MARGIN, 810, 24, name, true, '1 1 1'),
    text(MARGIN, 787, 10, subtitle, false, '1 0.92 0.88'),
  ];
}

function pageFooter(pageNumber: number, totalPages: number, generated: string) {
  return [
    line(MARGIN, 36, PAGE_WIDTH - MARGIN, 36),
    text(MARGIN, 20, 7.5, `Generated by MuviDB on ${generated}`, false, '0.45 0.47 0.5'),
    text(PAGE_WIDTH - 92, 20, 7.5, `Page ${pageNumber} of ${totalPages}`, false, '0.45 0.47 0.5'),
  ];
}

function buildPageContent(data: ProfessionalCvData) {
  const generated = data.generatedAt || new Date();
  const generatedDate = generated.toISOString().slice(0, 10);
  const credits = [...(data.credits || [])].sort((a, b) => (Number(b.films?.year) || 0) - (Number(a.films?.year) || 0));
  const shownCredits = data.format === 'resume' ? credits.slice(0, 12) : credits;
  const roles = (data.professionalRoles?.length ? data.professionalRoles : [data.person.known_for_department || 'Film professional']).map(roleLabel);
  const totalFilmViews = credits.reduce((sum, credit) => sum + (Number(credit.films?.view_count) || 0), 0);
  const years = credits.map((credit) => Number(credit.films?.year) || 0).filter(Boolean);
  const span = years.length ? `${Math.min(...years)} - ${Math.max(...years)}` : 'Not available';
  const subtitle = `${roles.join(' | ')}${data.person.nationality ? ` | ${ascii(data.person.nationality)}` : ''}`;
  const pages: string[][] = [[]];
  let page = pages[0];
  let y = 744;

  page.push(...pageHeader(data.person.name, subtitle));
  if (data.email) page.push(text(MARGIN, y, 9, data.email, false, '0.35 0.37 0.4'));
  if (data.person.slug) page.push(text(290, y, 9, `muvidb.com/people/${data.person.slug}`, false, '0.35 0.37 0.4'));
  y -= 28;

  page.push(text(MARGIN, y, 10, 'PROFESSIONAL SUMMARY', true, '0.96 0.29 0.08'));
  y -= 18;
  const biography = data.person.bio || data.person.biography || `${data.person.name} is a film professional with ${credits.length} verified credit${credits.length === 1 ? '' : 's'} recorded by MuviDB.`;
  const bioLines = wrap(biography, data.format === 'resume' ? 105 : 92).slice(0, data.format === 'resume' ? 3 : 4);
  for (const bioLine of bioLines) {
    page.push(text(MARGIN, y, 9.2, bioLine, false, '0.22 0.24 0.27'));
    y -= 14;
  }
  y -= 12;

  const metricTop = y;
  page.push(`0.97 0.97 0.975 rg 44 ${metricTop - 68} 507 68 re f`);
  page.push(text(58, metricTop - 20, 8, 'VERIFIED CREDITS', true, '0.45 0.47 0.5'), text(58, metricTop - 46, 17, number(credits.length), true));
  page.push(text(190, metricTop - 20, 8, 'PROFILE VIEWS', true, '0.45 0.47 0.5'), text(190, metricTop - 46, 17, number(data.person.profile_views), true));
  page.push(text(322, metricTop - 20, 8, 'FILM CATALOGUE VIEWS', true, '0.45 0.47 0.5'), text(322, metricTop - 46, 17, number(totalFilmViews), true));
  page.push(text(470, metricTop - 20, 8, 'CAREER SPAN', true, '0.45 0.47 0.5'), text(470, metricTop - 46, 11, span, true));
  y = metricTop - 92;

  const startFilmographyPage = () => {
    if (pages.length > 1) {
      page.push(...pageHeader(data.person.name, 'Detailed filmography'));
      y = 742;
    }
    page.push(text(MARGIN, y, 10, data.format === 'resume' ? 'SELECTED FILMOGRAPHY' : 'FILMOGRAPHY', true, '0.96 0.29 0.08'));
    y -= 22;
    page.push(text(MARGIN, y, 8, 'YEAR', true, '0.45 0.47 0.5'));
    page.push(text(88, y, 8, 'TITLE / CREDIT', true, '0.45 0.47 0.5'));
    page.push(text(455, y, 8, 'FILM VIEWS', true, '0.45 0.47 0.5'));
    y -= 10;
    page.push(line(MARGIN, y, PAGE_WIDTH - MARGIN, y));
    y -= 18;
  };
  startFilmographyPage();

  for (const credit of shownCredits) {
    if (y < 82) {
      pages.push([]);
      page = pages[pages.length - 1];
      startFilmographyPage();
    }
    const film = credit.films || {};
    const creditLine = `${roleLabel(credit.role || 'Credit')}${credit.character_name ? ` as ${ascii(credit.character_name)}` : ''}`;
    page.push(text(MARGIN, y, 9, film.year || '-', true));
    page.push(text(88, y, 9.4, ascii(film.title || 'Untitled production').slice(0, 62), true));
    page.push(text(455, y, 9, number(film.view_count), true));
    page.push(text(88, y - 13, 8.2, creditLine.slice(0, 75), false, '0.4 0.42 0.45'));
    if (film.average_rating) page.push(text(455, y - 13, 8, `Rating ${Number(film.average_rating).toFixed(1)}/10`, false, '0.4 0.42 0.45'));
    y -= 34;
    page.push(line(88, y + 8, PAGE_WIDTH - MARGIN, y + 8, '0.92 0.92 0.93'));
  }

  if (data.format === 'resume' && credits.length > shownCredits.length) {
    page.push(text(MARGIN, Math.max(y - 4, 58), 8, `${credits.length - shownCredits.length} additional verified credits available on MuviDB.`, false, '0.45 0.47 0.5'));
  }

  page.push(text(MARGIN, 52, 7.2, 'Analytics note: profile and film views are MuviDB-recorded catalogue metrics, not box-office or streaming revenue.', false, '0.45 0.47 0.5'));
  const totalPages = pages.length;
  pages.forEach((commands, index) => commands.push(...pageFooter(index + 1, totalPages, generatedDate)));
  return pages.map((commands) => commands.join('\n'));
}

export function generateProfessionalCvPdf(data: ProfessionalCvData) {
  const streams = buildPageContent(data);
  const pageIds = streams.map((_, index) => 5 + index * 2);
  const objects: string[] = [];
  objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
  objects[2] = `<< /Type /Pages /Count ${streams.length} /Kids [${pageIds.map((id) => `${id} 0 R`).join(' ')}] >>`;
  objects[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
  objects[4] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';
  streams.forEach((stream, index) => {
    const pageId = pageIds[index];
    const contentId = pageId + 1;
    objects[pageId] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentId} 0 R >>`;
    objects[contentId] = `<< /Length ${Buffer.byteLength(stream, 'ascii')} >>\nstream\n${stream}\nendstream`;
  });

  let pdf = '%PDF-1.4\n%MuviDB\n';
  const offsets: number[] = [0];
  for (let id = 1; id < objects.length; id += 1) {
    offsets[id] = Buffer.byteLength(pdf, 'ascii');
    pdf += `${id} 0 obj\n${objects[id]}\nendobj\n`;
  }
  const xref = Buffer.byteLength(pdf, 'ascii');
  pdf += `xref\n0 ${objects.length}\n0000000000 65535 f \n`;
  for (let id = 1; id < objects.length; id += 1) pdf += `${String(offsets[id]).padStart(10, '0')} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(pdf, 'ascii');
}
