export type CaptionBankCategory =
  | 'weekend_watchlist'
  | 'whats_on_stage'
  | 'film_conversation'
  | 'filmography'
  | 'critics_say'
  | 'where_to_watch'
  | 'behind_the_camera'
  | 'new_and_upcoming';

export const CAPTION_BANK_SOURCE = {
  title: 'MuviDB Posting Copy Vault — 800 Ideas',
  notionPageId: '3c4d77e5-82a9-818c-a6f3-d2a6ff458916',
  importedAt: '2026-08-23',
} as const;

export const CAPTION_BANK: Record<CaptionBankCategory, readonly string[]> = {
  "weekend_watchlist": [
    "Put [FILM] on your weekend watchlist. [One factual reason to consider it].",
    "One film for the weekend: [FILM]. [Short premise or verified selling point].",
    "If you only watch one African film this weekend, consider [FILM]. [Why it fits].",
    "Your weekend watch starts with [FILM]. [One useful detail].",
    "Need a film for tonight? Start with [FILM]. [Genre/premise].",
    "[FILM] is our pick for this weekend. [One factual reason].",
    "Friday night sorted: [FILM]. [Where to watch + concise reason].",
    "This weekend, we're putting [FILM] on the radar. [What makes it interesting].",
    "Save [FILM] for movie night. [One-sentence context].",
    "One title worth making time for this weekend: [FILM]. [Reason].",
    "[COUNT] MuviDB users have rated [FILM]. Here's why it may deserve a place on your list.",
    "With a [PERCENT]% audience score from [COUNT] ratings, [FILM] has people talking.",
    "[COUNT] viewers have already weighed in on [FILM]. Have you?",
    "[FILM] is sitting at [RATING]/10 from [COUNT] audience ratings. Weekend watch?",
    "The audience score on [FILM] caught our attention: [PERCENT]%. [One factual context line].",
    "[COUNT] reviews later, [FILM] is still holding a [RATING] score.",
    "A lot of viewers seem to agree on [FILM]: [PERCENT]% audience rating.",
    "[COUNT] people have rated [FILM] on MuviDB. The consensus? [SHORT VERIFIED SUMMARY].",
    "[FILM] has earned [COUNT] ratings so far. If you've seen it, does the score feel right?",
    "Before you choose tonight's film, here's one with [COUNT] audience ratings behind it: [FILM].",
    "In the mood for [MOOD]? Try [FILM] this weekend.",
    "If tonight calls for [GENRE/MOOD], [FILM] might be the right pick.",
    "For a [MOOD] kind of weekend: [FILM]. [One useful reason].",
    "Want something [ADJECTIVE] without spending 20 minutes scrolling? Try [FILM].",
    "Your mood says [MOOD]. Our pick says [FILM].",
    "Need something [FUNNY/TENSE/WARM/INTENSE]? [FILM] is worth a look.",
    "Three moods, three films: [FILM A], [FILM B], [FILM C]. Which one matches tonight?",
    "If you're after [MOOD 1], pick [FILM A]. If it's [MOOD 2], try [FILM B].",
    "Not every weekend needs a blockbuster. Try [FILM] if you're in the mood for [TYPE OF EXPERIENCE].",
    "A [GENRE] weekend starts here: [FILM].",
    "You may have scrolled past [FILM]. Here's one reason to go back.",
    "Heard of [FILM] but never pressed play? This weekend might be the time.",
    "[FILM] has been sitting in plain sight. Here's what makes it worth a second look.",
    "Before you start another rewatch, give [FILM] a look.",
    "One title you may have missed: [FILM]. [Short context].",
    "If [FILM] isn't already on your list, here's your reminder.",
    "A film you might know by name but not by story: [FILM].",
    "There's a good chance [FILM] slipped past your feed. Let's fix that.",
    "This is your sign to finally check out [FILM]. [Factual support].",
    "Not a new release. Still worth discovering: [FILM].",
    "If you liked [PERSON] in [KNOWN FILM], try [FILM] next.",
    "Watching for [ACTOR]? Add [FILM] to your list.",
    "[PERSON] appears in [FILM], and that may be your next watchlist entry.",
    "Follow the credits: from [FILM A] to [FILM B]. [PERSON] connects them.",
    "If [DIRECTOR]'s work is your thing, [FILM] belongs on the weekend list.",
    "One actor, another film to discover: [PERSON] in [FILM].",
    "Know [PERSON] from [FILM A]? Their credit in [FILM B] is worth exploring.",
    "The cast may be the reason you recognise [FILM]. The story may be why you stay.",
    "[FILM] brings together [PERSON A], [PERSON B] and [PERSON C]. Worth a weekend look?",
    "A familiar face, a different story: [PERSON] in [FILM].",
    "Weekend pick: [FILM], currently available on [PLATFORM].",
    "Looking for something you can actually watch tonight? [FILM] is on [PLATFORM].",
    "No searching required: [FILM] is currently streaming on [PLATFORM].",
    "Found your next watch? [FILM] is available on [PLATFORM].",
    "[FILM] + [PLATFORM] + this weekend. That's the plan.",
    "If [PLATFORM] is already open, search for [FILM].",
    "A weekend recommendation you can act on: [FILM], now on [PLATFORM].",
    "Start here, then press play: [FILM] is currently on [PLATFORM].",
    "Tonight's useful discovery: [FILM] is available via [PLATFORM].",
    "One less thing to search for: [FILM] → [PLATFORM].",
    "3 African films to put on your watchlist this weekend.",
    "5 films for when you don't know what to watch.",
    "3 films. 3 moods. Pick your weekend.",
    "A weekend watchlist with something for every mood.",
    "If your watchlist needs help, start with these [NUMBER] films.",
    "[NUMBER] African films worth adding before Monday.",
    "No endless scrolling. Here are [NUMBER] films to start with.",
    "From [GENRE A] to [GENRE B], here are [NUMBER] weekend picks.",
    "One watchlist, [NUMBER] different kinds of night.",
    "Save these [NUMBER] titles for the weekend.",
    "[FILM] works best if you're looking for [SPECIFIC EXPERIENCE].",
    "The reason we're recommending [FILM] isn't hype. It's [VERIFIED REASON].",
    "[FILM] is the kind of film that makes sense when you want [MOOD/GENRE].",
    "A watchlist pick with a clear reason: [FILM] for [REASON].",
    "If your weekend film needs [QUALITY], [FILM] is worth considering.",
    "[FILM] may not be the loudest title on your feed, but [FACT/ANGLE] makes it interesting.",
    "One thing [FILM] does well: [VERIFIED OBSERVATION]. That's enough to put it on our list.",
    "We're recommending [FILM] for [SPECIFIC AUDIENCE OR MOOD].",
    "Not every recommendation needs to be new. [FILM] still earns a place here because [REASON].",
    "A practical watchlist pick: [FILM], especially if you enjoyed [COMPARABLE VERIFIED TITLE/STYLE].",
    "[FILM] is on our list. Is it on yours?",
    "Seen [FILM] already? Give us the spoiler-free verdict.",
    "Would [FILM] make your weekend shortlist?",
    "If you've watched [FILM], what should first-time viewers know without spoilers?",
    "What would you pair with [FILM] for a two-film weekend?",
    "Who are you recommending [FILM] to?",
    "Is [FILM] a rewatch or a first-time watch for you?",
    "If [FILM] isn't your pick, what are you watching instead?",
    "Would you watch [FILM] for the cast, story, reviews or recommendation?",
    "Rate the weekend potential of [FILM] from 1–10.",
    "Weekend watch: [FILM].",
    "Tonight's pick: [FILM].",
    "Save this one: [FILM].",
    "Add [FILM] to the list.",
    "Your next watch may be [FILM].",
    "One film. One weekend. [FILM].",
    "Before Monday: watch [FILM].",
    "No scrolling tonight. Try [FILM].",
    "Watchlist update: [FILM] added.",
    "If you need one title, make it [FILM]."
  ],
  "whats_on_stage": [
    "On stage this week: [PRODUCTION]. [DATE] at [VENUE].",
    "If live theatre is on your list, put [PRODUCTION] on the radar.",
    "[PRODUCTION] takes the stage at [VENUE] on [DATE].",
    "Your next theatre night could be [PRODUCTION]. [Short verified premise].",
    "This weekend on stage: [PRODUCTION]. [VENUE] • [DATE].",
    "Live in [CITY]: [PRODUCTION]. [One useful detail].",
    "[PRODUCTION] is showing at [VENUE]. Here's what to know before you go.",
    "Looking for something beyond the cinema this weekend? [PRODUCTION] is on stage.",
    "One stage production worth knowing this week: [PRODUCTION].",
    "Curtain up on [PRODUCTION]. [DATE], [VENUE].",
    "[PRODUCTION] brings [THEME/PREMISE] to the stage this [DAY/WEEK].",
    "A story about [THEME] is coming alive on stage in [CITY]. Meet [PRODUCTION].",
    "What happens when [SHORT PREMISE]? [PRODUCTION] explores it live on stage.",
    "[PRODUCTION] turns [CORE CONFLICT] into a live theatre experience.",
    "Before the curtain rises, here's the story behind [PRODUCTION].",
    "[PRODUCTION] asks a simple question: [THEMATIC QUESTION]. See it at [VENUE].",
    "A live story about [THEME], performed at [VENUE]: [PRODUCTION].",
    "If [THEME] interests you, [PRODUCTION] may be your next theatre pick.",
    "From [CONFLICT] to [OUTCOME/QUESTION], [PRODUCTION] puts the story on stage.",
    "This isn't a screen story. [PRODUCTION] unfolds live at [VENUE].",
    "What's on stage: [PRODUCTION] • [DATE] • [TIME] • [VENUE].",
    "Planning a theatre night? [PRODUCTION] is showing on [DATE].",
    "Save the date: [PRODUCTION], [DATE] at [VENUE].",
    "Theatre plans, sorted: [PRODUCTION] at [VENUE], [TIME].",
    "Where: [VENUE]. When: [DATE]. What: [PRODUCTION].",
    "This week's theatre guide starts with [PRODUCTION].",
    "Before you make weekend plans: [PRODUCTION] is live at [VENUE].",
    "[CITY] theatre watch: [PRODUCTION] is on [DATE].",
    "Need the details for [PRODUCTION]? [DATE] • [VENUE] • [TIME].",
    "A simple theatre recommendation: [PRODUCTION], showing [DATE].",
    "[PRODUCTION] brings [PERSON A], [PERSON B] and [PERSON C] to the stage.",
    "See [PERSON] live in [PRODUCTION] at [VENUE].",
    "From screen to stage: [PERSON] appears in [PRODUCTION].",
    "The cast of [PRODUCTION] includes [PERSON A], [PERSON B] and [PERSON C].",
    "Behind [PRODUCTION]: [DIRECTOR/PLAYWRIGHT] leads the production.",
    "If you follow [PERSON]'s work, their stage credit in [PRODUCTION] is worth noting.",
    "Meet the creative team behind [PRODUCTION]: [KEY CREDITS].",
    "[PERSON] takes on [ROLE/CHARACTER] in [PRODUCTION].",
    "A theatre credit to add to [PERSON]'s body of work: [PRODUCTION].",
    "The people behind [PRODUCTION] are part of the reason to pay attention. [Key verified credits].",
    "African storytelling doesn't stop at the screen. [PRODUCTION] is one reason why.",
    "Film gets the feed. Theatre deserves a place there too. Today: [PRODUCTION].",
    "If you only discover African stories through film, add [PRODUCTION] to the picture.",
    "A reminder that some of the best stories are experienced live: [PRODUCTION].",
    "Today's discovery isn't a film. It's [PRODUCTION], live at [VENUE].",
    "Theatre discovery: [PRODUCTION] in [CITY].",
    "Put live performance on your discovery list with [PRODUCTION].",
    "One more way to experience African storytelling this week: [PRODUCTION].",
    "Beyond streaming and cinemas, there's [PRODUCTION] on stage.",
    "MuviDB theatre pick: [PRODUCTION]. [Short context].",
    "[COUNT] performances later, [PRODUCTION] is still drawing attention.",
    "[PRODUCTION] returns after [VERIFIED DEMAND/SELL-OUT FACT].",
    "With [COUNT] shows scheduled, [PRODUCTION] is giving audiences more chances to see it live.",
    "Audience demand has added [EXTRA DATE/SHOW] for [PRODUCTION].",
    "[PRODUCTION] has already played to [VERIFIED AUDIENCE/SOLD-OUT INFO]. Next stop: [VENUE].",
    "The response to [PRODUCTION] has led to [VERIFIED EXTENSION/RETURN].",
    "[COUNT] dates. One production: [PRODUCTION].",
    "If the [SELL-OUT/RETURN] is any indication, people are making time for [PRODUCTION].",
    "[PRODUCTION] is back on stage after [VERIFIED PRIOR RUN/RECEPTION].",
    "More dates have been added for [PRODUCTION]. Here's when to catch it.",
    "You know the actors. Have you seen them live? [PRODUCTION] is your chance.",
    "A title you may have seen on posters but not explored: [PRODUCTION].",
    "Before your next cinema trip, consider a theatre night with [PRODUCTION].",
    "What's happening at [VENUE] this week? [PRODUCTION].",
    "If [PRODUCTION] keeps appearing on your timeline, here's what it actually is.",
    "The stage production behind the poster: [PRODUCTION].",
    "One event you may want to know before making weekend plans: [PRODUCTION].",
    "[PRODUCTION] is happening in [CITY]. Did you know?",
    "A live performance hiding in your weekend options: [PRODUCTION].",
    "Not another movie recommendation. This time, we're sending you to the theatre.",
    "When was the last time you watched a live stage production? [PRODUCTION] is showing [DATE].",
    "Film or theatre this weekend? [PRODUCTION] makes the theatre case.",
    "Would you rather see [PERSON] on screen or live on stage?",
    "What's the last African stage production you saw?",
    "If you could bring one film story to the stage, what would it be?",
    "Are you a front-row theatre person or a cinema person?",
    "Would [PRODUCTION] make your weekend plans?",
    "Who would you take to see [PRODUCTION]?",
    "What makes you buy a theatre ticket: cast, story, venue or reviews?",
    "If you've seen [PRODUCTION], give us the spoiler-free verdict.",
    "[PRODUCTION] is worth noting for [SPECIFIC VERIFIED REASON].",
    "The interesting thing about [PRODUCTION] is [VERIFIED ANGLE].",
    "[PRODUCTION] arrives at [VENUE] with [CONTEXT].",
    "For audiences interested in [THEME/GENRE], [PRODUCTION] offers a live option this week.",
    "A useful addition to this week's culture calendar: [PRODUCTION].",
    "[PRODUCTION] gives [CITY] audiences a chance to see [PERSON/STORY] live.",
    "Theatre pick of the week: [PRODUCTION], because [FACTUAL REASON].",
    "A current stage production to know: [PRODUCTION]. [Why now].",
    "If your weekend plan needs something different, [PRODUCTION] is a strong alternative.",
    "[PRODUCTION] is part of this week's African storytelling beyond the screen.",
    "On stage: [PRODUCTION].",
    "Tonight at [VENUE]: [PRODUCTION].",
    "This weekend: [PRODUCTION].",
    "Live in [CITY]: [PRODUCTION].",
    "Save the date for [PRODUCTION].",
    "Curtain call: [PRODUCTION].",
    "Your theatre pick: [PRODUCTION].",
    "What's on stage? [PRODUCTION].",
    "A live story to discover: [PRODUCTION].",
    "Stage watch: [PRODUCTION] at [VENUE]."
  ],
  "film_conversation": [
    "What African film made you fall in love with African cinema?",
    "What film do you wish you could watch again for the first time?",
    "Which African film stayed with you long after the credits rolled?",
    "What film reminds you of a specific time in your life?",
    "Which film did you watch as a child that you still remember clearly?",
    "What African film changed the way you saw a particular actor?",
    "Which film surprised you the most the first time you saw it?",
    "What film did someone recommend to you that actually lived up to the hype?",
    "Which film have you rewatched more than any other?",
    "What's one African film you still think about years later?",
    "Recommend one African film. No spoilers. Just the title and one reason.",
    "What's the most underrated African film you've seen?",
    "What film should MuviDB put on everyone's radar?",
    "Name one film you think deserves a bigger audience.",
    "What's your go-to African film recommendation for someone who says they don't know where to start?",
    "One comedy. One drama. One thriller. What are your picks?",
    "What African film would you recommend to someone watching African cinema for the first time?",
    "What's one film you recommend without needing to explain why?",
    "Give us a film recommendation based only on mood: [MOOD].",
    "What's the hidden gem in your watch history?",
    "Was [CHARACTER] right or wrong in [FILM]?",
    "Which decision by [CHARACTER] changed everything in [FILM]?",
    "Would you have made the same choice as [CHARACTER]?",
    "Who's the real villain in [FILM]?",
    "Which character deserved a different ending?",
    "Who had the strongest character arc in [FILM]?",
    "Which character frustrated you the most, and why?",
    "Who would you trust least in [FILM]?",
    "Which character would you want a spin-off about?",
    "Whose perspective would completely change [FILM] if the story were retold through them?",
    "Who gave the best performance in [FILM]?",
    "What performance made you forget you were watching an actor?",
    "Which actor completely owned their role in [FILM]?",
    "Which supporting performance deserved more attention?",
    "What role made you become a fan of [PERSON]?",
    "Which actor surprised you most in [FILM]?",
    "What's [PERSON]'s strongest performance so far?",
    "Which performance carried [FILM] for you?",
    "Who had the best chemistry in [FILM]?",
    "Which casting choice turned out better than you expected?",
    "What makes a film memorable to you: story, performance, visuals or dialogue?",
    "Did [FILM] stick the ending?",
    "What's one film with an ending you still debate?",
    "Which African film has your favourite opening scene?",
    "What film had a great idea but could have been executed better?",
    "Which film had the strongest dialogue you've heard recently?",
    "What movie twist genuinely caught you off guard?",
    "Which film gets better the more you think about it?",
    "What story would you like to see more often in African cinema?",
    "What's a familiar storyline you think filmmakers can retire for a while?",
    "Your rating for [FILM]: /10?",
    "[FILM] is rated [RATING] on MuviDB. Too high, too low or fair?",
    "The audience score for [FILM] is [PERCENT]%. Does that match your experience?",
    "[COUNT] people have rated [FILM]. What score would you add?",
    "One-word review of [FILM]?",
    "Finish the sentence: [FILM] was __.",
    "Would you recommend [FILM] to someone who hasn't seen it? Why?",
    "Is [FILM] a watch-once film or a rewatch?",
    "What's the strongest thing about [FILM]?",
    "What's the one thing you would change about [FILM]?",
    "[FILM A] or [FILM B]? You can only keep one.",
    "Cinema or streaming for a film like [FILM]?",
    "Actor-led film or story-led film?",
    "Trailer first or go in completely blind?",
    "Reviews before watching or reviews after?",
    "Comedy or thriller tonight?",
    "Big ensemble cast or one strong lead?",
    "Rewatch an old favourite or discover something new?",
    "Subtitles or dubbed audio when both are available?",
    "Opening weekend or wait for audience reviews?",
    "What makes you click play on a film you've never heard of?",
    "How many films are currently sitting on your watchlist?",
    "Do you finish a film you aren't enjoying or switch it off?",
    "How long do you give a film before deciding it isn't for you?",
    "Do actors influence what you watch more than directors do?",
    "What's the last film you watched because of a social media recommendation?",
    "Do ratings affect whether you watch a movie?",
    "What's more useful to you: trailer, synopsis, reviews or cast list?",
    "Do you usually know what you're watching before movie night starts?",
    "What's the biggest reason you abandon a film halfway?",
    "What kind of African film do you want to see more of?",
    "Which African film industry outside your country should more people explore?",
    "What's one film role people don't appreciate enough?",
    "Which director's next project are you most curious about?",
    "What makes a great cinema experience for you?",
    "Should films reveal more of their crew in marketing, not just the cast?",
    "Which actor would you like to see take on a completely different kind of role?",
    "What's one genre African cinema should experiment with more?",
    "What makes you trust a film recommendation?",
    "Who influences your viewing choices most: friends, critics, creators or algorithms?",
    "What are you watching tonight?",
    "Last African film you watched?",
    "Best film you've seen this month?",
    "What film is currently at the top of your watchlist?",
    "Which actor are you watching closely right now?",
    "What film deserves a sequel?",
    "What sequel didn't need to happen?",
    "Best cinema experience you've had this year?",
    "What film did everyone love that just didn't work for you?",
    "What film did you love that everyone else seemed to dislike?"
  ],
  "filmography": [
    "You know [PERSON] from [KNOWN FILM]. But their filmography goes much further.",
    "If [KNOWN FILM] is where you discovered [PERSON], here are three more credits to know.",
    "One familiar role can lead you into an entire filmography. Start with [PERSON].",
    "Know [PERSON] from [FILM A]? Their credits also include [FILM B], [FILM C] and [FILM D].",
    "[FILM A] may be the title you remember, but [PERSON]'s work stretches far beyond it.",
    "Before [FILM A], there was [FILM B]. After it came [FILM C]. Follow [PERSON]'s credits.",
    "The role you know is only one line in [PERSON]'s filmography.",
    "If one film made you notice [PERSON], these credits show where else to look.",
    "Start with [FILM A]. Then follow [PERSON] to [FILM B] and [FILM C].",
    "A familiar face, a longer body of work: [PERSON].",
    "One person. Three films. Where are you starting? [FILM A], [FILM B], [FILM C].",
    "Three credits from [PERSON]'s filmography worth knowing.",
    "Four [PERSON] credits to add to your watchlist.",
    "From [FILM A] to [FILM D], here are four stops in [PERSON]'s filmography.",
    "[PERSON] across three very different films: [FILM A], [FILM B], [FILM C].",
    "Build a [PERSON] watchlist with these [NUMBER] verified credits.",
    "If you're exploring [PERSON]'s work, start with these three titles.",
    "A quick route through [PERSON]'s filmography: [FILM A] → [FILM B] → [FILM C].",
    "Three films. One connecting credit: [PERSON].",
    "Your [PERSON] filmography starter pack: [FILM A], [FILM B], [FILM C].",
    "Did you know [PERSON] worked on [FILM]?",
    "You may know [PERSON] as an actor, but their credits also include [OTHER ROLE] on [FILM].",
    "A credit you might have missed: [PERSON] in [FILM].",
    "[PERSON] and [FILM] are connected by a credit you may not have noticed.",
    "Before you knew [PERSON] from [FILM A], they appeared/worked on [FILM B].",
    "One lesser-known [PERSON] credit: [FILM].",
    "If [FILM] surprised you, check the credits: [PERSON] is there.",
    "[PERSON]'s filmography includes a title you may not expect: [FILM].",
    "A hidden connection in the credits: [PERSON] → [FILM].",
    "You watched [FILM]. Did you notice [PERSON]'s credit?",
    "From [EARLIER FILM] to [RECENT FILM], here's a look at [PERSON]'s screen journey.",
    "[YEAR A] to [YEAR B]: [PERSON]'s credits tell a story of their own.",
    "One career, different chapters: [FILM A], [FILM B], [FILM C].",
    "Trace [PERSON]'s work through these three verified credits.",
    "An early credit, a breakthrough title and a recent project: [PERSON]'s filmography in three stops.",
    "The evolution of [PERSON]'s work, one credit at a time.",
    "[PERSON]'s filmography moves from [GENRE/ROLE A] to [GENRE/ROLE B].",
    "A timeline through [PERSON]'s selected credits.",
    "Where did you first discover [PERSON]? Their credit history starts earlier than many remember.",
    "From supporting roles to [CURRENT ROLE/STATUS], follow [PERSON]'s credits.",
    "Actor, writer, producer: [PERSON]'s credits go beyond one role.",
    "[PERSON] appears in front of the camera and behind it. Here's where.",
    "Don't stop at the acting credits. [PERSON] also worked as [ROLE] on [FILM].",
    "One person, multiple roles: [PERSON] across [FILM A] and [FILM B].",
    "[PERSON]'s filmography isn't just about appearances. The credits include [ROLE].",
    "From [ROLE A] to [ROLE B], [PERSON] has contributed to films in more than one way.",
    "The filmography tells a bigger story when you read the role column. [PERSON] is a good example.",
    "[PERSON] has credits as [ROLE A], [ROLE B] and [ROLE C].",
    "You may recognise the face. The behind-the-scenes credits are worth knowing too.",
    "A filmography that crosses roles: [PERSON].",
    "From [GENRE A] to [GENRE B], [PERSON]'s credits show range.",
    "[PERSON] in romance, drama and thriller: three credits, three different worlds.",
    "Think you know [PERSON]'s type? These films suggest otherwise.",
    "One performer, very different roles: [FILM A] and [FILM B].",
    "If you've only seen [PERSON] in [GENRE], try [FILM] next.",
    "[PERSON]'s filmography moves across [GENRES]. Where do you think they work best?",
    "A range check: [PERSON] in [FILM A], [FILM B] and [FILM C].",
    "Three credits that show different sides of [PERSON]'s work.",
    "From comic timing to dramatic weight, [PERSON]'s credits cover both.",
    "Which genre brings out the best in [PERSON]? These credits give you options.",
    "[COUNT] MuviDB users have visited/rated titles featuring [PERSON]. Start with these three.",
    "[PERSON]'s most-rated MuviDB credit is [FILM] with [COUNT] ratings.",
    "Among [PERSON]'s credits, [FILM] currently has the strongest audience score at [PERCENT]%.",
    "[COUNT] audience ratings across these [PERSON] titles. Which one did you score highest?",
    "The audience favourite in [PERSON]'s filmography right now: [FILM].",
    "[FILM] leads [PERSON]'s selected credits with a [RATING] audience score.",
    "If ratings guide your watchlist, start [PERSON]'s filmography with [FILM].",
    "[COUNT] reviews later, [FILM] remains one of [PERSON]'s most-discussed credits.",
    "Which [PERSON] film has the strongest audience response? Right now, it's [FILM].",
    "A data-led way into [PERSON]'s filmography: start with the audience favourite.",
    "[FILM A] and [FILM B] have one thing in common: [PERSON].",
    "Seen both [FILM A] and [FILM B]? You followed [PERSON]'s filmography without realising it.",
    "One credit connects these two films: [PERSON].",
    "From [FILM A] to [FILM B], follow the person in the credits.",
    "If you liked [FILM A], [PERSON]'s credit in [FILM B] gives you a natural next watch.",
    "The recommendation path is in the credits: [FILM A] → [PERSON] → [FILM B].",
    "A film can lead to a person, then to another film. Today that trail is [FILM A] → [PERSON] → [FILM B].",
    "You don't always need an algorithm. Sometimes one credit is enough.",
    "Follow [PERSON] from [FILM A] into [FILM B].",
    "Two films, one shared person, one new discovery path.",
    "Which [PERSON] credit did you discover them through?",
    "What's [PERSON]'s best film so far?",
    "Which [PERSON] role deserves more attention?",
    "What film should someone watch first to understand [PERSON]'s work?",
    "Which [PERSON] credit surprised you most?",
    "If you could keep only one [PERSON] film, which one stays?",
    "Which [PERSON] collaboration would you like to see again?",
    "What kind of role should [PERSON] try next?",
    "Which credit made you take [PERSON] seriously as a performer/filmmaker?",
    "Have you seen more of [PERSON]'s work than you realised? Count the credits you've watched.",
    "The filmography: [PERSON].",
    "Follow the credits: [PERSON].",
    "More than one film: [PERSON].",
    "Three [PERSON] credits to know.",
    "Where have you seen [PERSON]?",
    "One person. Many stories. [PERSON].",
    "A deeper look at [PERSON]'s credits.",
    "Beyond [KNOWN FILM]: [PERSON].",
    "Your next [PERSON] watch starts here.",
    "Explore [PERSON], credit by credit."
  ],
  "critics_say": [
    "What the critics are saying about [FILM]. [CRITIC/PUBLICATION] highlights [POINT].",
    "[CRITIC]'s take on [FILM]: [SHORT ACCURATE PARAPHRASE].",
    "Before you watch [FILM], here's one critical perspective worth reading.",
    "[PUBLICATION] reviewed [FILM], praising [ASPECT] while questioning [ASPECT].",
    "One review. One perspective. [CRITIC] on [FILM].",
    "[CRITIC] sees [FILM] as [ACCURATE SUMMARY].",
    "A critic's view of [FILM]: [POINT]. Do you see it the same way?",
    "[FILM] through [CRITIC]'s eyes: [PARAPHRASED OBSERVATION].",
    "The review of [FILM] that caught our attention today comes from [CRITIC].",
    "[CRITIC] on [FILM]: strong on [X], less convinced by [Y].",
    "Same film. Two very different reads. [CRITIC A] says [A]; [CRITIC B] says [B].",
    "Critics agree on [X], but split on [Y] in [FILM].",
    "[CRITIC A] praised [ASPECT]. [CRITIC B] wasn't convinced. Where do you land?",
    "Two reviews, one film: [FILM].",
    "The debate around [FILM] comes down to [ISSUE].",
    "[FILM] has critics divided over [ASPECT].",
    "One critic sees [STRENGTH]. Another sees [WEAKNESS]. That's the conversation around [FILM].",
    "What happens when two critics watch the same film and notice completely different things? [FILM].",
    "[CRITIC A] vs [CRITIC B] on [FILM]: [SHORT CONTRAST].",
    "The critical conversation around [FILM] isn't unanimous. Here's where the views split.",
    "[FILM] currently holds a [RATING] critic score on MuviDB.",
    "[COUNT] critic reviews give [FILM] an average of [RATING].",
    "The critics' average for [FILM]: [RATING]. Fair?",
    "[COUNT] reviews later, [FILM] is sitting at [RATING].",
    "Critic score: [RATING]. Audience score: [RATING]. Same film, different response.",
    "[FILM]'s critic score is [RATING], compared with [AUDIENCE RATING] from audiences.",
    "The data says critics are [MORE/LESS] positive on [FILM] than audiences.",
    "A [RATING] critic average puts [FILM] in [CONTEXT].",
    "How much should critic scores matter? [FILM] is currently at [RATING].",
    "Critics have rated [FILM] [RATING]. Now the audience gets the final word.",
    "“[SHORT PERMITTED QUOTE]” — [CRITIC], on [FILM].",
    "One line from [CRITIC]'s review of [FILM] says a lot: “[SHORT QUOTE]”.",
    "[CRITIC] called [FILM] “[SHORT QUOTE]”. Here's the wider point behind it.",
    "A line worth pulling from [FILM]'s reviews: “[SHORT QUOTE]”.",
    "“[SHORT QUOTE]” — a critic's take on [FILM]. Do you agree?",
    "The sentence that sums up [CRITIC]'s view of [FILM]: “[SHORT QUOTE]”.",
    "One critic, one sharp line on [FILM]: “[SHORT QUOTE]”.",
    "[PUBLICATION]'s review of [FILM] includes this observation: “[SHORT QUOTE]”.",
    "A memorable review line from [FILM]: “[SHORT QUOTE]”.",
    "Critic quote of the day: “[SHORT QUOTE]” on [FILM].",
    "Critics keep coming back to [PERSON]'s performance in [FILM].",
    "[CRITIC] singles out [PERSON] as [ACCURATE PERFORMANCE SUMMARY].",
    "One thing critics seem to agree on: [PERSON]'s work in [FILM].",
    "The performance getting critical attention in [FILM]: [PERSON].",
    "[CRITIC] praises [PERSON] for [SPECIFIC PERFORMANCE QUALITY].",
    "Even in a mixed review, [PERSON]'s performance stood out for [CRITIC].",
    "What did critics make of [PERSON] in [FILM]? Here's one view.",
    "[PERSON]'s performance is one of the strongest points in [CRITIC]'s review of [FILM].",
    "The review conversation around [FILM] keeps circling back to [PERSON].",
    "If you're watching [FILM] for one performance, critics point to [PERSON].",
    "The critics aren't only talking about the cast. [FILM]'s [CINEMATOGRAPHY/EDITING/WRITING] is part of the conversation.",
    "[CRITIC] highlights [CRAFT AREA] as one of [FILM]'s strongest elements.",
    "A review worth reading for its take on [FILM]'s direction: [CRITIC].",
    "What works behind the camera in [FILM]? [CRITIC] points to [CRAFT].",
    "The critical praise for [FILM] extends to [CREW ROLE/PERSON].",
    "[FILM]'s visuals drew attention from [CRITIC] for [SPECIFIC POINT].",
    "[CRITIC] argues that [FILM]'s writing is [ACCURATE SUMMARY].",
    "The editing of [FILM] is central to [CRITIC]'s review.",
    "One overlooked part of the [FILM] reviews: what critics say about the crew.",
    "A critic's note on the craft behind [FILM]: [POINT].",
    "Critics say [X]. Audiences say [Y]. [FILM] is a good reminder that both can be true.",
    "[FILM] has a [CRITIC SCORE] critic score and [AUDIENCE SCORE] audience score. Which side are you closer to?",
    "The gap between critic and audience reactions to [FILM] is [DIFFERENCE].",
    "Critics are cooler on [FILM] than audiences. Have you seen it?",
    "Audiences are tougher on [FILM] than critics. What did you think?",
    "A film where critics and viewers mostly agree: [FILM].",
    "The critic/audience split on [FILM] is worth looking at.",
    "Who got [FILM] right for you: critics or audiences?",
    "Two scores, one film. [FILM]: critics [X], audiences [Y].",
    "Ratings tell two stories about [FILM]. Which one matches yours?",
    "Before you press play on [FILM], here's the criticism worth knowing.",
    "One thing to watch for in [FILM], according to [CRITIC]: [POINT].",
    "If reviews influence your watchlist, here's the critical read on [FILM].",
    "Wondering whether [FILM] is worth your time? Start with what critics noticed.",
    "A spoiler-free critical note before [FILM]: [POINT].",
    "The reviews of [FILM] keep mentioning [ASPECT]. Here's why.",
    "What are critics seeing in [FILM] that trailers don't show?",
    "One review may change what you pay attention to in [FILM].",
    "Before you form your own view, here's [CRITIC]'s read of [FILM].",
    "Watch first or read reviews first? If it's the latter, start here with [FILM].",
    "Do critics influence what you watch?",
    "Should a critic score ever stop you from watching a film?",
    "What's one film where you completely disagreed with the critics?",
    "Which matters more to you: critic score or audience score?",
    "Have you ever changed your mind about a film after reading a review?",
    "What makes you trust a film critic?",
    "Do you read reviews before or after watching?",
    "Can a negative review make you more curious about a film?",
    "What's the best film review you've read recently?",
    "Do you prefer critics who score films or critics who avoid ratings?",
    "Critics on [FILM].",
    "One review of [FILM] worth reading.",
    "The critical take: [FILM].",
    "What [CRITIC] saw in [FILM].",
    "Same film. Different opinions.",
    "The review conversation around [FILM].",
    "Before you watch: critics on [FILM].",
    "Critic score check: [FILM].",
    "One perspective on [FILM].",
    "Read, watch, decide: [FILM]."
  ],
  "where_to_watch": [
    "Now streaming: [FILM] on [PLATFORM].",
    "[FILM] is currently available on [PLATFORM].",
    "Looking for [FILM]? You can watch it on [PLATFORM].",
    "Found the film. Here's where to watch it: [PLATFORM].",
    "[FILM] → [PLATFORM]. That's the current viewing route.",
    "You can currently find [FILM] on [PLATFORM].",
    "Streaming update: [FILM] is on [PLATFORM].",
    "One less thing to search for: [FILM] is available via [PLATFORM].",
    "Where can you watch [FILM]? Start with [PLATFORM].",
    "Tonight's useful discovery: [FILM] is streaming on [PLATFORM].",
    "New on [PLATFORM]: [FILM].",
    "[FILM] has arrived on [PLATFORM].",
    "Now available to stream: [FILM] on [PLATFORM].",
    "[FILM] joins [PLATFORM] from [DATE].",
    "A new African film to find on [PLATFORM]: [FILM].",
    "[PLATFORM] just added [FILM]. Here's what to know.",
    "Streaming arrival: [FILM] is now on [PLATFORM].",
    "If [FILM] was on your watchlist, it is now available on [PLATFORM].",
    "Your wait may be over: [FILM] is now streaming on [PLATFORM].",
    "[FILM] is newly available on [PLATFORM] as of [DATE].",
    "[FILM] comes to [PLATFORM] on [DATE].",
    "Save the date: [FILM] starts streaming on [PLATFORM] [DATE].",
    "Streaming soon: [FILM] → [PLATFORM] → [DATE].",
    "[DATE] is the date if you're waiting to watch [FILM] on [PLATFORM].",
    "[FILM] lands on [PLATFORM] this [DAY/WEEK].",
    "Your watchlist reminder: [FILM] arrives on [PLATFORM] [DATE].",
    "Coming to [PLATFORM]: [FILM], from [DATE].",
    "If you've been waiting for [FILM], [PLATFORM] gets it on [DATE].",
    "[FILM] has a streaming date: [DATE] on [PLATFORM].",
    "Countdown to [FILM] on [PLATFORM]: [DATE].",
    "[FILM] is currently available on [PLATFORM A] and [PLATFORM B].",
    "Two ways to watch [FILM] right now: [PLATFORM A] or [PLATFORM B].",
    "Where to watch [FILM]: [PLATFORM A] • [PLATFORM B].",
    "You have options for [FILM]: [PLATFORM A] and [PLATFORM B].",
    "[FILM] is available across [NUMBER] verified viewing destinations.",
    "Pick your platform: [FILM] is on [PLATFORM A] and [PLATFORM B].",
    "One film, multiple viewing options: [FILM].",
    "Current availability for [FILM]: [PLATFORM A], [PLATFORM B], [PLATFORM C].",
    "No single-platform problem here: [FILM] is currently available on [PLATFORMS].",
    "Your current options for [FILM], all in one place: [PLATFORMS].",
    "You can legally watch [FILM] on YouTube via [OFFICIAL CHANNEL].",
    "Free to watch: [FILM] is currently available on [OFFICIAL YOUTUBE CHANNEL].",
    "A legal YouTube discovery: [FILM].",
    "No subscription needed for this one: [FILM] is on [OFFICIAL CHANNEL].",
    "Looking for a free African film to watch? [FILM] is legally available on YouTube.",
    "[FILM] is currently free to watch via [OFFICIAL CHANNEL].",
    "YouTube watch: [FILM], available from [OFFICIAL CHANNEL].",
    "A film you can watch tonight without another subscription: [FILM].",
    "Official upload alert: [FILM] is available on [CHANNEL].",
    "Save this legal YouTube watch: [FILM].",
    "[FILM] is currently showing in cinemas. Check MuviDB for current locations and showtimes.",
    "Planning to see [FILM] in cinemas? Here's where it's currently showing.",
    "Cinema watch: [FILM] is showing at [CINEMA/LOCATIONS].",
    "[FILM] is on the big screen this week. Current showtime information is on MuviDB.",
    "Before heading out for [FILM], check the current cinema and showtime details.",
    "Where to see [FILM] in cinemas: [VERIFIED LOCATIONS].",
    "[FILM] has current screenings in [CITY/REGION].",
    "Cinema plans? [FILM] is currently listed at [CINEMA].",
    "Theatrical availability update: [FILM] is showing in [LOCATION].",
    "Check before you go: [FILM]'s current cinema details are available on MuviDB.",
    "[COUNT] people have checked/rated [FILM], and here's where you can watch it now: [PLATFORM].",
    "With [COUNT] audience ratings behind it, [FILM] is currently streaming on [PLATFORM].",
    "[FILM] is one of the most-viewed MuviDB titles this [PERIOD]. You can currently watch it on [PLATFORM].",
    "A [PERCENT]% audience score and a current home on [PLATFORM]: [FILM].",
    "If the [COUNT] ratings made you curious, [FILM] is currently on [PLATFORM].",
    "People are searching for [FILM]. The current viewing destination is [PLATFORM].",
    "[COUNT] MuviDB interactions later, here's the useful part: [FILM] is available on [PLATFORM].",
    "Audience interest in [FILM] is high this week. Watch it on [PLATFORM].",
    "One of this week's most-discovered titles on MuviDB: [FILM], currently on [PLATFORM].",
    "The audience signal says [FILM] is worth a look. The viewing route says [PLATFORM].",
    "[FILM], starring [PERSON A] and [PERSON B], is currently streaming on [PLATFORM].",
    "If you're looking for [PERSON]'s work, [FILM] is available on [PLATFORM].",
    "A [GENRE] starring [CAST], now on [PLATFORM]: [FILM].",
    "[DIRECTOR]'s [FILM] is currently available to watch on [PLATFORM].",
    "The film behind [SHORT PREMISE] is [FILM], and it's currently on [PLATFORM].",
    "If [SHORT PREMISE] sounds like your kind of film, [FILM] is on [PLATFORM].",
    "Watch [PERSON] in [FILM], currently available on [PLATFORM].",
    "[FILM] brings together [CAST]. You can currently find it on [PLATFORM].",
    "A useful next watch if you like [PERSON]: [FILM] on [PLATFORM].",
    "Follow the credits from [KNOWN FILM] to [FILM], currently streaming on [PLATFORM].",
    "Have you already watched [FILM] on [PLATFORM]?",
    "Is [FILM] going on your list now that you know where to find it?",
    "What film should we check the current availability for next?",
    "Which platform do you use most for African films?",
    "What's one title you've been searching everywhere for?",
    "Do you prefer cinema releases or waiting for streaming?",
    "What African film do you wish were easier to find legally?",
    "Seen [FILM]? Tell us whether it's worth the stream.",
    "Would knowing exactly where a film is available make you more likely to watch it?",
    "What's the last film MuviDB helped you locate?",
    "Where to watch: [FILM].",
    "Streaming now: [FILM].",
    "Watch [FILM] on [PLATFORM].",
    "[FILM] is now on [PLATFORM].",
    "Found it: [FILM] → [PLATFORM].",
    "Your streaming update: [FILM].",
    "Now available: [FILM].",
    "Watchlist to watch-now: [FILM].",
    "Current viewing destination: [PLATFORM].",
    "Before you search everywhere: check MuviDB."
  ],
  "behind_the_camera": [
    "You know [FILM]. Meet the director behind it: [PERSON].",
    "[PERSON] directed [FILM]. Here are two more credits worth knowing.",
    "The person calling the shots on [FILM]: [PERSON].",
    "If [FILM] worked for you, follow the director credit to [PERSON]'s other work.",
    "Behind [FILM]'s direction is [PERSON]. [One factual context line].",
    "One director, three films: [PERSON] → [FILM A], [FILM B], [FILM C].",
    "A filmography behind the camera: [PERSON].",
    "[PERSON]'s directing credit on [FILM] is a useful place to start.",
    "Know the film. Know the director: [PERSON] on [FILM].",
    "[FILM] didn't direct itself. Meet [PERSON].",
    "The story of [FILM] starts with a writing credit: [PERSON].",
    "Meet the writer behind [FILM]: [PERSON].",
    "If the dialogue in [FILM] stayed with you, check the writing credits.",
    "[PERSON] wrote [FILM]. Their other credits include [FILM B] and [FILM C].",
    "Before actors perform the words, someone writes them. On [FILM], that credit belongs to [PERSON].",
    "One screenplay, one name to know: [PERSON] on [FILM].",
    "The writing credit connecting [FILM A] and [FILM B]: [PERSON].",
    "Story credit spotlight: [PERSON], writer of [FILM].",
    "If [FILM]'s story is what caught you, follow the writer: [PERSON].",
    "Behind the plot of [FILM] is [PERSON].",
    "You know the title. Meet one of the producers who helped make it happen: [PERSON].",
    "[PERSON] produced [FILM]. Here's where else their credit appears.",
    "Production credit spotlight: [PERSON] on [FILM].",
    "The producer connection between [FILM A] and [FILM B]: [PERSON].",
    "A producer can connect very different films. [PERSON] is credited on [FILMS].",
    "Behind [FILM]'s production is [PERSON].",
    "One producer, multiple stories: [PERSON].",
    "Follow the production credits from [FILM A] to [FILM B].",
    "[PERSON]'s producer credits include [FILM A], [FILM B] and [FILM C].",
    "A name behind several titles you may know: [PERSON].",
    "Who shaped the look of [FILM]? Cinematography by [PERSON].",
    "The framing, lighting and camera language of [FILM] carry a credit: [PERSON].",
    "If you noticed how [FILM] looked, meet its cinematographer: [PERSON].",
    "Visual credit spotlight: [PERSON], cinematographer on [FILM].",
    "[FILM]'s images didn't happen by accident. [PERSON] handled cinematography.",
    "One craft credit worth reading: [PERSON] on [FILM].",
    "From [FILM A] to [FILM B], [PERSON]'s cinematography connects the two.",
    "The person behind the camera on [FILM]: [PERSON].",
    "If visuals are what you remember from [FILM], the cinematography credit belongs to [PERSON].",
    "A cinematographer to know: [PERSON]. Start with [FILM].",
    "The pace of [FILM] has an editing credit behind it: [PERSON].",
    "Meet the editor of [FILM]: [PERSON].",
    "Cuts, rhythm, structure: [PERSON] edited [FILM].",
    "An editor can change how a story feels. On [FILM], that role was [PERSON].",
    "Editing credit spotlight: [PERSON] on [FILM].",
    "If [FILM] moved at the right pace for you, read the editing credit: [PERSON].",
    "[PERSON]'s editing credits connect [FILM A] and [FILM B].",
    "One name behind the final shape of [FILM]: [PERSON].",
    "The edit is part of the storytelling. [PERSON] handled it on [FILM].",
    "Behind the final cut of [FILM]: [PERSON].",
    "The world of [FILM] was built through more than sets and cameras. [PERSON] handled [ROLE].",
    "Costume credit spotlight: [PERSON] on [FILM].",
    "If the wardrobe in [FILM] caught your eye, the credit goes to [PERSON].",
    "Production design helped define [FILM]'s world. Meet [PERSON].",
    "One craft detail you noticed, one crew member to know: [PERSON], [ROLE] on [FILM].",
    "The visual world behind [FILM] includes [PERSON]'s work as [ROLE].",
    "From costume to character, [PERSON]'s credit on [FILM] matters.",
    "[FILM]'s [COSTUME/MAKEUP/PRODUCTION DESIGN] credit: [PERSON].",
    "A behind-the-camera role worth knowing today: [ROLE], handled by [PERSON] on [FILM].",
    "Meet one of the people who made [FILM] look like [FILM]: [PERSON].",
    "The sound of [FILM] has a name behind it: [PERSON], [ROLE].",
    "Music credit spotlight: [PERSON] on [FILM].",
    "If [FILM]'s score stayed with you, follow the music credit to [PERSON].",
    "Behind the soundscape of [FILM]: [PERSON].",
    "One film, one sound credit worth knowing: [PERSON].",
    "[PERSON] handled [SOUND/MUSIC ROLE] on [FILM].",
    "The audio side of filmmaking deserves names too. Today: [PERSON] on [FILM].",
    "From [FILM A] to [FILM B], [PERSON]'s music/sound credit connects both.",
    "A soundtrack can carry a scene. The credit on [FILM] goes to [PERSON].",
    "Listen to the credits too: [PERSON], [ROLE] on [FILM].",
    "What does a [ROLE] actually do? [SIMPLE EXPLANATION]. On [FILM], that role belongs to [PERSON].",
    "The credits you usually scroll past: today's role is [ROLE].",
    "A film crew role in plain language: [ROLE] = [SIMPLE EXPLANATION].",
    "Next time the credits roll, look for [ROLE]. On [FILM], that's [PERSON].",
    "Not sure what a [ROLE] does? [ONE-SENTENCE EXPLANATION]. Meet [PERSON] from [FILM].",
    "Film role 101: [ROLE]. Example: [PERSON] on [FILM].",
    "Behind every [CRAFT RESULT] is often a [ROLE]. On [FILM], that person is [PERSON].",
    "One crew title worth understanding today: [ROLE].",
    "[ROLE] explained through a real credit: [PERSON] on [FILM].",
    "Read the credits differently: [ROLE], [PERSON], [FILM].",
    "[FILM A] and [FILM B] share more than an audience. [PERSON] worked on both as [ROLE].",
    "One crew credit connects these films: [PERSON], [ROLE].",
    "Follow the crew trail: [FILM A] → [PERSON] → [FILM B].",
    "You watched both films. Did you notice the same [ROLE] credit? [PERSON].",
    "The database connection today: [PERSON] behind [FILM A] and [FILM B].",
    "If you liked the craft in [FILM A], follow [PERSON]'s credit into [FILM B].",
    "Same crew member, different films: [PERSON] on [FILM A] and [FILM B].",
    "A recommendation hidden in the crew credits: [FILM A] → [PERSON] → [FILM B].",
    "Behind-the-camera filmography: [PERSON] connects [NUMBER] verified titles.",
    "Some of the best discovery paths start in the crew list. Today: [PERSON].",
    "Behind the camera: [PERSON].",
    "Meet the crew: [PERSON], [ROLE].",
    "One credit to know: [PERSON].",
    "Who made [FILM]? Start with [PERSON].",
    "Read the credits: [PERSON].",
    "Beyond the cast: [PERSON].",
    "The craft behind [FILM]: [PERSON].",
    "A name behind the work: [PERSON].",
    "Today's crew spotlight: [PERSON].",
    "Every film. Every credit. Today: [PERSON]."
  ],
  "new_and_upcoming": [
    "New poster for [FILM]. [Release/platform detail if verified].",
    "First look: the new poster for [FILM].",
    "[FILM] has a new poster ahead of its [DATE] release.",
    "Poster reveal: [FILM], coming [DATE/PLATFORM].",
    "A new look at [FILM] before release day.",
    "Official poster: [FILM]. [One verified context line].",
    "The poster for [FILM] is here. The film arrives [DATE].",
    "New artwork for [FILM], starring [CAST].",
    "[FILM] just unveiled its latest poster. Here's what we know so far.",
    "Poster drop: [FILM]. [DATE] • [PLATFORM/CINEMA].",
    "The trailer for [FILM] is out now.",
    "First trailer: [FILM], coming [DATE].",
    "[FILM] has released its official trailer ahead of [DATE].",
    "Trailer watch: [FILM]. [One factual premise line].",
    "The first look at [FILM] is here.",
    "New trailer for [FILM], starring [CAST].",
    "[FILM] gives us a closer look with its new trailer.",
    "Trailer released: [FILM] → [DATE/PLATFORM].",
    "The trailer is live. Here's what it reveals about [FILM] without spoilers.",
    "Watch the new trailer for [FILM]. Release date: [DATE].",
    "[FILM] releases on [DATE].",
    "Save the date: [FILM] arrives [DATE].",
    "Release date confirmed: [FILM] → [DATE].",
    "[FILM] has an official release date: [DATE].",
    "Mark the calendar for [FILM]: [DATE].",
    "[DATE] is the date for [FILM].",
    "The wait for [FILM] now has a date: [DATE].",
    "[FILM] arrives in cinemas/on [PLATFORM] [DATE].",
    "One date to add to your film calendar: [DATE] for [FILM].",
    "[FILM] lands [DATE]. Here's what we know about it.",
    "[FILM] comes to [PLATFORM] on [DATE].",
    "Streaming premiere: [FILM] → [PLATFORM] → [DATE].",
    "[FILM] will stream on [PLATFORM] from [DATE].",
    "Prime/Netflix/YouTube/etc. date confirmed for [FILM]: [DATE].",
    "[FILM] is heading to [PLATFORM]. Save [DATE].",
    "Your streaming calendar has a new date: [FILM] on [PLATFORM], [DATE].",
    "[FILM] gets a [PLATFORM] release on [DATE].",
    "Coming soon to [PLATFORM]: [FILM].",
    "If [FILM] is on your watchlist, it arrives on [PLATFORM] [DATE].",
    "[FILM] moves from announcement to watch date: [DATE] on [PLATFORM].",
    "[FILM] opens in cinemas on [DATE].",
    "Cinema release confirmed: [FILM], [DATE].",
    "[FILM] heads to the big screen from [DATE].",
    "Save [DATE] for [FILM] in cinemas.",
    "Theatrical release: [FILM] arrives [DATE].",
    "[FILM] is coming to cinemas. Here's the date: [DATE].",
    "Opening [DATE]: [FILM].",
    "[FILM]'s cinema run begins [DATE].",
    "A new cinema date for your calendar: [FILM], [DATE].",
    "See [FILM] on the big screen from [DATE].",
    "[PERSON] joins the cast of [FILM].",
    "Cast update: [FILM] adds [PERSON].",
    "[FILM] will star [PERSON A], [PERSON B] and [PERSON C].",
    "New casting announcement for [FILM]: [PERSON].",
    "The cast of [FILM] is taking shape. Latest name: [PERSON].",
    "[PERSON] has been announced for [FILM].",
    "A new credit for [PERSON]: [FILM].",
    "[FILM] brings together [CAST]. Here's the verified lineup so far.",
    "Casting news: [PERSON] is attached to [FILM].",
    "Another name joins [FILM]: [PERSON].",
    "[PERSON] will direct [FILM].",
    "Behind-the-camera update: [PERSON] joins [FILM] as [ROLE].",
    "[FILM] has announced [PERSON] as [ROLE].",
    "Production credit update: [PERSON] on [FILM].",
    "The team behind [FILM] now includes [PERSON], [ROLE].",
    "[PERSON] is writing/producing/directing [FILM].",
    "A key crew announcement for [FILM]: [PERSON] as [ROLE].",
    "[FILM] adds [PERSON] behind the camera.",
    "New verified credit: [PERSON] → [ROLE] → [FILM].",
    "The people making [FILM] are coming into focus. Latest credit: [PERSON].",
    "Here's what [FILM] is about. [Concise verified premise].",
    "New details on [FILM]: [VERIFIED PREMISE].",
    "Before [FILM] arrives, here's the story we know so far.",
    "[FILM] follows [SHORT VERIFIED PREMISE].",
    "The premise behind [FILM]: [PREMISE].",
    "If [PREMISE] sounds like your kind of story, keep [FILM] on the radar.",
    "A little more context on [FILM] before release day.",
    "[FILM] is built around [CORE VERIFIED CONFLICT].",
    "The story behind the poster/trailer: [FILM] follows [PREMISE].",
    "What do we actually know about [FILM]? Start with the premise.",
    "[COUNT] trailer views later, [FILM] is clearly drawing attention ahead of [DATE].",
    "[FILM]'s trailer has crossed [COUNT] views. Release: [DATE].",
    "[COUNT] people have interacted with/rated the title on MuviDB ahead of release.",
    "Interest around [FILM] is climbing, with [COUNT] verified views/interactions.",
    "The announcement for [FILM] has generated [COUNT] verified engagements/views.",
    "With [COUNT] trailer views, [FILM] is one of the releases people are watching closely.",
    "[FILM] is trending among [VERIFIED SOURCE/AUDIENCE SIGNAL]. Here's when it arrives.",
    "The audience attention is already there. [FILM] arrives [DATE].",
    "[COUNT] views and counting on the official trailer for [FILM].",
    "A release attracting early attention: [FILM]. [Verified metric + date].",
    "Coming soon: [FILM].",
    "New poster: [FILM].",
    "Trailer out now: [FILM].",
    "Release date: [FILM] → [DATE].",
    "Cast update: [FILM].",
    "First look: [FILM].",
    "Save the date for [FILM].",
    "New film alert: [FILM].",
    "On the radar: [FILM].",
    "What we know so far: [FILM]."
  ]
};

function normalizeKey(value: string): string {
  return value.toUpperCase().replace(/[^A-Z0-9]+/g, ' ').trim();
}

function firstValue(...values: unknown[]): string | undefined {
  for (const value of values) {
    if (typeof value === 'string' && value.trim()) return value.trim();
    if (typeof value === 'number' && Number.isFinite(value)) return String(value);
  }
  return undefined;
}

export function captionBankCategoryForSeries(seriesSlug: string, candidate?: any): CaptionBankCategory {
  const slug = (seriesSlug || '').toLowerCase().replace(/-/g, '_');
  if (slug.includes('stage') || slug.includes('theatre') || candidate?.type === 'play') return 'whats_on_stage';
  if (slug.includes('weekend') || slug.includes('watchlist')) return 'weekend_watchlist';
  if (slug.includes('critic') || slug.includes('review') || slug.includes('take')) return 'critics_say';
  if (slug.includes('behind') || slug.includes('camera') || slug.includes('crew') || slug.includes('craft')) return 'behind_the_camera';
  if (slug.includes('upcoming') || slug.includes('announcement') || slug.includes('release_alert')) return 'new_and_upcoming';
  if (slug.includes('where_to_watch') || slug.includes('streaming')) return 'where_to_watch';
  if (candidate?.type === 'person' || slug.includes('filmography') || slug.includes('face') || slug.includes('actor') || slug.includes('talent')) return 'filmography';
  return 'film_conversation';
}

export function buildVerifiedCaptionValues(candidate: any): Record<string, string> {
  const data = candidate?.data || {};
  const knownFor = Array.isArray(data.knownFor) ? data.knownFor : [];
  const topCast = Array.isArray(data.topCast) ? data.topCast : [];
  const directors = Array.isArray(data.directors) ? data.directors : [];
  const genres = Array.isArray(data.genres) ? data.genres : [];
  const isPerson = candidate?.type === 'person';
  const isPlay = candidate?.type === 'play';
  const title = firstValue(candidate?.name);
  const filmTitle = !isPerson && !isPlay ? title : firstValue(knownFor[0]?.title);
  const personName = isPerson ? title : firstValue(topCast[0]?.name);
  const platform = firstValue(data.platformDisplayName, data.watchAvailability);
  const date = firstValue(data.release_date, data.run_start_date);
  const role = firstValue(data.department, candidate?.category, data.known_for_department);
  const values: Record<string, string | undefined> = {
    FILM: filmTitle,
    TITLE: title,
    PERSON: personName,
    PLATFORM: platform,
    DATE: date,
    YEAR: firstValue(data.year),
    ROLE: role,
    CREDIT: firstValue(knownFor[0]?.title),
    'KNOWN FILM': firstValue(knownFor[0]?.title),
    'FILM A': firstValue(knownFor[0]?.title),
    'FILM B': firstValue(knownFor[1]?.title),
    'FILM C': firstValue(knownFor[2]?.title),
    GENRE: firstValue(genres[0]),
    CAST: topCast.slice(0, 3).map((entry: any) => entry?.name).filter(Boolean).join(', ') || undefined,
    'PERSON A': firstValue(topCast[0]?.name),
    'PERSON B': firstValue(topCast[1]?.name),
    DIRECTOR: firstValue(directors[0]?.name),
    VENUE: firstValue(data.venue),
    CITY: firstValue(data.city),
    COUNTRY: firstValue(candidate?.country, data.nationality, data.country),
    RATING: firstValue(data.criticReview?.rating, data.rating),
    QUOTE: firstValue(data.criticReview?.quote, data.quote),
    CRITIC: firstValue(data.criticReview?.criticName, data.criticName),
    PUBLICATION: firstValue(data.criticReview?.publication, data.publication),
    PERCENT: firstValue(data.liked_percent),
  };
  return Object.fromEntries(
    Object.entries(values)
      .filter((entry): entry is [string, string] => Boolean(entry[1]))
      .map(([key, value]) => [normalizeKey(key), value]),
  );
}

export function resolveCaptionStarter(template: string, values: Record<string, string>): string | null {
  let unresolved = false;
  const rendered = template.replace(/\[([^\]]+)\]/g, (_match, rawKey: string) => {
    const value = values[normalizeKey(rawKey)];
    if (!value) {
      unresolved = true;
      return '';
    }
    return value;
  });
  return unresolved ? null : rendered.replace(/\s+/g, ' ').trim();
}

function stableHash(value: string): number {
  let hash = 2166136261;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
}

function isTemplateSemanticallyEligible(template: string, category: CaptionBankCategory, candidate: any): boolean {
  const text = template.toLowerCase();
  const data = candidate?.data || {};
  const lifecycle = data.lifecycle;
  const platform = String(data.platform || data.platformDisplayName || '').toLowerCase();

  // These claims require evidence stronger than a title, poster URL, or profile row.
  if (/\b(acclaimed|award-winning|iconic|legendary)\b/i.test(template)) return false;

  if (category === 'where_to_watch') {
    if (/\b(new on|has arrived|newly available|just added|wait may be over|streaming arrival)\b/i.test(template)) return false;
    if (/\b(people are searching|audience interest|most-viewed|most-discovered|audience signal|trending)\b/i.test(template)) return false;
    if (/\b(youtube|free to watch|no subscription|official upload)\b/i.test(template) && !platform.includes('youtube')) return false;
    if (/\b(cinema|cinemas|showtime|big screen|theatrical)\b/i.test(template) && lifecycle !== 'now_in_cinemas') return false;
  }

  if (category === 'new_and_upcoming') {
    const placeholders = [...template.matchAll(/\[([^\]]+)\]/g)].map(match => normalizeKey(match[1]));
    if (!placeholders.includes('FILM') || placeholders.some(key => !['FILM', 'DATE', 'YEAR'].includes(key))) return false;
    if (/\b(audience|attention|interest|buzz|anticipated|trending)\b/i.test(template)) return false;
    if (/\b(new poster|poster reveal|first look)\b/i.test(template)) return false;
    if (/\b(cast update|cast reveal|joins|added to the cast|announced|confirmed)\b/i.test(template)) return false;
    if (/\btrailer\b/i.test(template) && !data.trailer_youtube_id && !data.trailer_external_url) return false;
    if (/\b(release date|save the date|arrives|releases|lands in|comes to cinemas)\b/i.test(template) && !data.release_date) return false;
  }

  return true;
}

export function selectCaptionBankStarters(input: {
  seriesSlug: string;
  candidate: any;
  limit?: number;
}): { category: CaptionBankCategory; starters: string[] } {
  const category = captionBankCategoryForSeries(input.seriesSlug, input.candidate);
  const values = buildVerifiedCaptionValues(input.candidate);
  let eligible = CAPTION_BANK[category]
    .filter(template => isTemplateSemanticallyEligible(template, category, input.candidate))
    .map(template => resolveCaptionStarter(template, values))
    .filter((starter): starter is string => Boolean(starter));

  // The vault's own rule for Where to Watch is utility first: the opening must
  // name both the title and verified destination, never just ask a generic question.
  if (category === 'where_to_watch' && values.FILM && values.PLATFORM) {
    eligible = eligible.filter(starter =>
      starter.toLowerCase().includes(values.FILM.toLowerCase()) &&
      starter.toLowerCase().includes(values.PLATFORM.toLowerCase()),
    );
  }

  const limit = Math.max(1, Math.min(input.limit || 8, 20));
  if (eligible.length <= limit) return { category, starters: eligible };

  const seed = stableHash(`${input.seriesSlug}:${input.candidate?.id || input.candidate?.name || ''}`);
  const start = seed % eligible.length;
  const starters = Array.from({ length: limit }, (_, offset) => eligible[(start + offset) % eligible.length]);
  return { category, starters };
}
