/**
 * Extracts the handful of Solar icons the Social Studio cards use into
 * `api/_lib/social_icons.ts`.
 *
 * `@iconify-json/solar/icons.json` is 6MB and holds 7,400 icons. Importing it
 * from a Vercel function would add that to every cold start, so only the icons
 * actually placed on a card are inlined.
 *
 * Run after adding a new icon:  node scripts/generate_social_icons.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';

const SOURCE = 'node_modules/@iconify-json/solar/icons.json';
const TARGET = 'api/_lib/social_icons.ts';

// Semantic name -> Solar icon name. Matches the outlined icons in the mockups.
const WANTED = {
  globe: 'global-linear',
  star: 'star-linear',
  arrowRight: 'arrow-right-linear',
  clapperboard: 'clapperboard-linear',
  users: 'users-group-rounded-linear',
  calendar: 'calendar-linear',
  clock: 'clock-circle-linear',
  trophy: 'cup-star-linear',
  videocamera: 'videocamera-linear',
  armchair: 'armchair-linear',
  mask: 'mask-happly-linear',
};

const set = JSON.parse(readFileSync(SOURCE, 'utf8'));
const missing = Object.values(WANTED).filter(name => !set.icons[name]);
if (missing.length) throw new Error(`Missing Solar icons: ${missing.join(', ')}`);

const entries = Object.entries(WANTED)
  .map(([key, name]) => {
    const icon = set.icons[name];
    const w = icon.width ?? set.width ?? 24;
    const h = icon.height ?? set.height ?? 24;
    return `  ${key}: { name: '${name}', width: ${w}, height: ${h}, body: ${JSON.stringify(icon.body)} },`;
  })
  .join('\n');

writeFileSync(
  TARGET,
  `// GENERATED by scripts/generate_social_icons.mjs — do not edit by hand.
// Source: @iconify-json/solar (the icon set used across the MuviDB app).

export type SocialIconName = keyof typeof SOCIAL_ICONS;

export const SOCIAL_ICONS = {
${entries}
} as const;
`,
  'utf8',
);

console.log(`wrote ${TARGET} with ${Object.keys(WANTED).length} icons`);
