-- Shared pause/resume control and worker monitoring for the credit harvester.
--
-- The dashboard cannot stop or start an operating-system process on another
-- machine. It can, however, tell every live worker to finish its current film
-- and stop claiming new work. Workers also publish heartbeats and durable log
-- entries so the admin dashboard can show progress and failures.

create table if not exists public.credit_harvest_control (
  id smallint primary key default 1 check (id = 1),
  paused boolean not null default false,
  pause_requested_at timestamptz,
  resumed_at timestamptz,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

insert into public.credit_harvest_control (id, paused)
values (1, false)
on conflict (id) do nothing;

create table if not exists public.credit_harvest_workers (
  worker_id text primary key,
  machine_name text not null,
  process_id integer,
  status text not null default 'starting'
    check (status in ('starting', 'idle', 'running', 'paused', 'stopping', 'stopped', 'failed')),
  current_job_id uuid references public.credit_harvest_jobs(id) on delete set null,
  current_film_id uuid references public.films(id) on delete set null,
  processed_count integer not null default 0,
  failure_count integer not null default 0,
  last_message text,
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  stopped_at timestamptz
);

create index if not exists credit_harvest_workers_last_seen_idx
  on public.credit_harvest_workers (last_seen_at desc);

create table if not exists public.credit_harvest_logs (
  id bigint generated by default as identity primary key,
  worker_id text,
  level text not null default 'info'
    check (level in ('info', 'success', 'warning', 'error')),
  event_type text not null,
  message text not null,
  job_id uuid references public.credit_harvest_jobs(id) on delete set null,
  film_id uuid references public.films(id) on delete set null,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists credit_harvest_logs_created_idx
  on public.credit_harvest_logs (created_at desc);
create index if not exists credit_harvest_logs_error_idx
  on public.credit_harvest_logs (created_at desc)
  where level = 'error';

alter table public.credit_harvest_jobs
  add column if not exists worker_id text,
  add column if not exists heartbeat_at timestamptz;

create index if not exists credit_harvest_jobs_running_heartbeat_idx
  on public.credit_harvest_jobs (heartbeat_at)
  where status = 'running';

alter table public.credit_harvest_control enable row level security;
alter table public.credit_harvest_workers enable row level security;
alter table public.credit_harvest_logs enable row level security;

drop policy if exists "credit_harvest_control admin" on public.credit_harvest_control;
create policy "credit_harvest_control admin" on public.credit_harvest_control
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "credit_harvest_workers admin read" on public.credit_harvest_workers;
create policy "credit_harvest_workers admin read" on public.credit_harvest_workers
  for select to authenticated using (public.is_admin());

drop policy if exists "credit_harvest_logs admin read" on public.credit_harvest_logs;
create policy "credit_harvest_logs admin read" on public.credit_harvest_logs
  for select to authenticated using (public.is_admin());

grant select, insert, update, delete on public.credit_harvest_control to authenticated;
grant select on public.credit_harvest_workers to authenticated;
grant select on public.credit_harvest_logs to authenticated;
grant all on public.credit_harvest_control to service_role;
grant all on public.credit_harvest_workers to service_role;
grant all on public.credit_harvest_logs to service_role;
grant usage, select on sequence public.credit_harvest_logs_id_seq to service_role;

-- One audited entry point for the dashboard's Pause/Resume button.
create or replace function public.set_credit_harvest_paused(p_paused boolean)
returns public.credit_harvest_control
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.credit_harvest_control;
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;

  insert into public.credit_harvest_control (
    id,
    paused,
    pause_requested_at,
    resumed_at,
    updated_at,
    updated_by
  )
  values (
    1,
    p_paused,
    case when p_paused then now() else null end,
    case when p_paused then null else now() end,
    now(),
    auth.uid()
  )
  on conflict (id) do update
  set
    paused = excluded.paused,
    pause_requested_at = case
      when excluded.paused then now()
      else credit_harvest_control.pause_requested_at
    end,
    resumed_at = case
      when excluded.paused then credit_harvest_control.resumed_at
      else now()
    end,
    updated_at = now(),
    updated_by = auth.uid()
  returning * into result;

  insert into public.credit_harvest_logs (
    worker_id,
    level,
    event_type,
    message
  )
  values (
    'dashboard',
    'info',
    case when p_paused then 'pause_requested' else 'resume_requested' end,
    case
      when p_paused then 'Pause requested from the admin dashboard'
      else 'Resume requested from the admin dashboard'
    end
  );

  return result;
end;
$$;

revoke all on function public.set_credit_harvest_paused(boolean) from public;
grant execute on function public.set_credit_harvest_paused(boolean) to authenticated;

-- Manual recovery for jobs abandoned by a dead laptop or killed worker.
create or replace function public.recover_stale_credit_harvest_jobs(
  p_stale_after_minutes integer default 60
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  recovered_count integer;
  stale_minutes integer := greatest(coalesce(p_stale_after_minutes, 60), 15);
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;

  update public.credit_harvest_jobs
  set
    status = 'pending',
    worker_id = null,
    heartbeat_at = null,
    started_at = null,
    error = concat_ws(
      ' | ',
      nullif(error, ''),
      'Recovered by admin after stale worker heartbeat'
    )
  where status = 'running'
    and coalesce(heartbeat_at, started_at, created_at)
      < now() - make_interval(mins => stale_minutes);

  get diagnostics recovered_count = row_count;

  insert into public.credit_harvest_logs (
    worker_id,
    level,
    event_type,
    message,
    details
  )
  values (
    'dashboard',
    case when recovered_count > 0 then 'warning' else 'info' end,
    'stale_jobs_recovered',
    format('Recovered %s stale harvest job(s)', recovered_count),
    jsonb_build_object('stale_after_minutes', stale_minutes)
  );

  return recovered_count;
end;
$$;

revoke all on function public.recover_stale_credit_harvest_jobs(integer) from public;
grant execute on function public.recover_stale_credit_harvest_jobs(integer) to authenticated;

-- Replace the zero-argument claim function with an optional worker id. Existing
-- workers can still call it with no arguments, and immediately gain central
-- pause support because the pause check lives in the database.
drop function if exists public.claim_credit_harvest_job();
drop function if exists public.claim_credit_harvest_job(text);

create function public.claim_credit_harvest_job(p_worker_id text default null)
returns table (
  id uuid,
  film_id uuid,
  channel_id uuid,
  attempts smallint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(
    (select control.paused from public.credit_harvest_control as control where control.id = 1),
    false
  ) then
    return;
  end if;

  return query
  with next_job as (
    select job.id
    from public.credit_harvest_jobs as job
    where job.status = 'pending'
    order by job.priority desc, job.created_at asc
    for update skip locked
    limit 1
  )
  update public.credit_harvest_jobs as job
  set
    status = 'running',
    attempts = job.attempts + 1,
    started_at = now(),
    worker_id = nullif(trim(p_worker_id), ''),
    heartbeat_at = now()
  from next_job
  where job.id = next_job.id
  returning job.id, job.film_id, job.channel_id, job.attempts;
end;
$$;

revoke all on function public.claim_credit_harvest_job(text) from public;
grant execute on function public.claim_credit_harvest_job(text) to service_role;

comment on table public.credit_harvest_control is
  'Singleton pause/resume state shared by every credit-harvest worker.';
comment on table public.credit_harvest_workers is
  'Worker process heartbeats and current activity for the admin monitor.';
comment on table public.credit_harvest_logs is
  'Durable worker and dashboard events shown in the credit-harvest monitor.';
